---
title: Önemli Dokümanlar (Endüstri Mühendisliği)
linktitle: Endüstri Mühendisliği
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  ekonomi:
    parent: Dokümanlar
    weight: 22

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 22
---

<br>

## Telegram Kanalı
Dersle ilgili önemli duyurulardan zamanında haberdar olabilmeniz için [Telegram](https://telegram.org/) adlı uygulama içinde haberleşme kanalı oluşturulmuştur. Detaylı bilgiye aşağıdaki dokümanlardan ulaşabilirsiniz.  

- [Telegram Kanalı Duyurusu](`r paste0(ekonomi.path, "IE/Ekonomi_Telegram Kanali Duyurusu_Bilgilendirme.pdf")`)
- [QR Kod - Telefon İçin](`r paste0(ekonomi.path, "IE/Ekonomi_Telegram Kanali Duyurusu_Ilan.pdf")`)

## Ders Planı ve Önemli Günler
<!-- - [Ders Planı - 1. Öğretim](`r paste0(ekonomi.path, "IE/Ekonomi_1O - Ders Plani (Kara).pdf")`) -->
<!-- - [Önemli Günler - 1. Öğretim](`r paste0(ekonomi.path, "IE/Ekonomi_1O - Onemli Gunler (Kara).pdf")`) -->
<!-- - [Ders Planı - 2. Öğretim](`r paste0(ekonomi.path, "IE/Ekonomi_2O - Ders Plani (Kara).pdf")`) -->
<!-- - [Önemli Günler - 2. Öğretim](`r paste0(ekonomi.path, "IE/Ekonomi_2O - Onemli Gunler (Kara).pdf")`) -->

| 1. Öğretim | 2. Öğretim |
| :--- | :--- |
| [Ders Planı](`r paste0(ekonomi.path, "IE/Ekonomi_1O - Ders Plani (Kara).pdf")`) | [Ders Planı](`r paste0(ekonomi.path, "IE/Ekonomi_2O - Ders Plani (Kara).pdf")`) |
| [Önemli Günler](`r paste0(ekonomi.path, "IE/Ekonomi_1O - Onemli Gunler (Kara).pdf")`) | [Önemli Günler](`r paste0(ekonomi.path, "IE/Ekonomi_2O - Onemli Gunler (Kara).pdf")`) |

## Ders Kitabı
- [Kitap Seçimi Açıklaması](`r paste0(ekonomi.path, "Ekonomi_Kitap Secimi Aciklamasi (Kara).pdf")`)

## Ders Değerlendirme Anketi
- [Ders Değerlendirme Anketi - Açıklama](`r paste0(ekonomi.path, "IE/Ekonomi_Ders Degerlendirme Anketi.pdf")`)
- [Ders Değerlendirme Anketi - Link](https://forms.gle/CVsdVSfWUKiWVMjh8)
