---
title: Important Documents (Electrical-Electronics Engineering)
linktitle: Electrical-Electronics Engineering
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  economics:
    parent: Documents
    weight: 22

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 22
---

```{r emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
On the page you are reviewing, the icons and the contents they refer are as follows: `r emo::ji(tr)` <font color="red">**Turkish**</font>, `r emo::ji(eng)` <font color="red">**English**</font>, `r emo::ji(to.be.updated)` <font color="red">**Will be Updated**</font>, `r emo::ji(in.progress)` <font color="red">**In Progress**</font>, and `r emo::ji(outdated)` <font color="red">**No Longer Valid**</font>.
{{% /alert %}}

## Telegram Channel
To inform you about the important announcements related to the course on time, an announcement channel is created in the [Telegram](https://telegram.org/) app. The detailed information can be found on documents below.  

- [Telegram Channel Announcement](`r paste0(economics.path, "EE/Economics_Telegram Channel Announcement_Info.pdf")`) `r emo::ji(eng)`
- [QR Code - For Phones](`r paste0(economics.path, "EE/Economics_Telegram Channel Announcement_Flyer.pdf")`) `r emo::ji(eng)`

## Syllabus and Important Dates
| Normal Education | Secondary Education |
| :--- | :--- |
| [Syllabus](`r paste0(economics.path, "EE/Economics_NE - Syllabus (Kara).pdf")`) `r emo::ji(eng)` `r emo::ji(to.be.updated)` | [Syllabus](`r paste0(economics.path, "EE/Economics_SE - Syllabus (Kara).pdf")`) `r emo::ji(eng)` `r emo::ji(to.be.updated)` |
| [Important Dates](`r paste0(economics.path, "EE/Economics_NE - Important Dates (Kara).pdf")`) `r emo::ji(eng)` `r emo::ji(to.be.updated)` | [Important Dates](`r paste0(economics.path, "EE/Economics_SE - Important Dates (Kara).pdf")`) `r emo::ji(eng)` `r emo::ji(to.be.updated)` |

## Course Book
- [Book Selection Explanation](`r paste0(economics.path, "Economics_Book Selection Explanation.pdf")`) `r emo::ji(eng)`

## Course Evaluation Survey
- [Course Evaluation Survey - Explanation](`r paste0(economics.path, "EE/Economics_Course Evaluation Survey.pdf")`) `r emo::ji(tr)`
- [Course Evaluation Survey - Link](https://forms.gle/EEd4Whw9pqEPxzeY7) `r emo::ji(tr)`
