---
title: Problem Sets and Exams
linktitle: Problem Sets and Exams
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  economics:
    parent: 
    weight: 40

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 40
---

```{r Settings.Emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
On the page you are reviewing, the icons and the contents they refer are as follows: `r emo::ji(tr)` <font color="red">**Turkish**</font>, `r emo::ji(eng)` <font color="red">**English**</font>, `r emo::ji(to.be.updated)` <font color="red">**Will be Updated**</font>, `r emo::ji(in.progress)` <font color="red">**In Progress**</font>, and `r emo::ji(outdated)` <font color="red">**No Longer Valid**</font>.
{{% /alert %}}

## Problem Sets
- [CANVAS'ta Online Çoktan Seçmeli Ödev Nasıl Yapılır?]() `r emo::ji(tr)``r emo::ji(in.progress)`
    - [DYS'de Online Çoktan Seçmeli Ödev Nasıl Yapılır?](https://www.youtube.com/watch?v=OOqC0JrtOaI&feature=youtu.be) `r emo::ji(tr)``r emo::ji(outdated)`

## Exams
| Türkçe `r emo::ji(tr)` | İngilizce `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Ara Sınav - İnceleme](`r paste0(ekonomi.path, "Ekonomi_-_Ara_Sinav_Inceleme.pdf")`) | [Midterm Exam - Review](`r paste0(economics.path, "Economics_-_Midterm_Exam_Review.pdf")`) |
| [Final Sınavı - İnceleme](`r paste0(ekonomi.path, "Ekonomi_-_Final_Sinavi_Inceleme.pdf")`) | [Final Exam - Review](`r paste0(economics.path, "Economics_-_Final_Exam_Review.pdf")`) |

- [CANVAS'ta Online Çoktan Seçmeli Sınav Nasıl Yapılır?]() `r emo::ji(tr)``r emo::ji(in.progress)`
    - [DYS'de Online Çoktan Seçmeli Sınav Nasıl Yapılır?](https://www.youtube.com/watch?v=V_Oyg-WGoK4&feature=youtu.be) `r emo::ji(tr)``r emo::ji(outdated)`
- [CANVAS'a Online Klasik Sınav Nasıl Yüklenir]() `r emo::ji(tr)``r emo::ji(in.progress)`
    - [DYS'ye Online Klasik Sınav Nasıl Yüklenir?](https://www.youtube.com/watch?v=wsUB6-fTxA8&feature=youtu.be) `r emo::ji(tr)``r emo::ji(outdated)`
