---
title: Lecture Notes
linktitle: Lecture Notes
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  economics:
    parent: 
    weight: 50

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 50
---

```{r Settings.Emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
On the page you are reviewing, the icons and the contents they refer are as follows: `r emo::ji(tr)` <font color="red">**Turkish**</font>, `r emo::ji(eng)` <font color="red">**English**</font>, `r emo::ji(to.be.updated)` <font color="red">**Will be Updated**</font>, `r emo::ji(in.progress)` <font color="red">**In Progress**</font>, and `r emo::ji(outdated)` <font color="red">**No Longer Valid**</font>.
{{% /alert %}}

## Week #1
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=2X_-CiNAr6w&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=1) | [Video - Part #1](https://www.youtube.com/watch?v=rEZfMve6Vm0&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=1) |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=jeNwjaAVs4o&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=2) | [Video - Part #2](https://www.youtube.com/watch?v=1wAclMe5c6M&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=2) |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_1.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_1.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_1_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_1_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_1_CS.pdf")`) | [Worksheet](`r paste0(economics.path, "Economics_-_Week_1_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_1_CS_Cevap.pdf")`) | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_1_Worksheet_Solution.pdf")`) |

## Week #2
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video](https://www.youtube.com/watch?v=JIpF9at8540&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=3) | [Video](https://www.youtube.com/watch?v=Z347BG3oFn4&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=3) |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_2.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_2.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_2_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_2_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_2_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_2_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_2_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_2_Worksheet_Solution.pdf")`) |

## Week #3
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=akfocLbvXjM&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=4) | [Video - Part #1](https://www.youtube.com/watch?v=T7EQqHhbAgk&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=4) |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=Ykk_oeJiE_I&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=5) | [Video - Part #2](https://www.youtube.com/watch?v=Xudjskkv47U&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=5) |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_3.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_3.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_3_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_3_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_3_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_3_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_3_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_3_Worksheet_Solution.pdf")`) |
| [Çalışma Soruları Cevaplar - Grafiksel](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_3_CS_Cevap__Grafiksel.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions - Graphical](`r paste0(economics.path, "Economics_-_Week_3_Worksheet_Solution__Graphical.pdf")`) |

## Week #4
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=ggTcdWCzMq0&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=6) | [Video - Part #1](https://www.youtube.com/watch?v=KKY6iOTOQHI&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=6) |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=n4lnYcVw4z0&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=7) | [Video - Part #2](https://www.youtube.com/watch?v=E4YhqVQ3TDk&list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg&index=7) |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_4.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_4.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_4_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_4_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_4_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_4_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_4_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_4_Worksheet_Solution.pdf")`) |

## Week #5
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=tHFcUR5oW-Q&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=8) | [Video - Part #1]() `r emo::ji(in.progress)` |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=KT5QKjJ7ub0&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=9) | [Video - Part #2]() `r emo::ji(in.progress)` |
| [Video - Bölüm #3](https://www.youtube.com/watch?v=etsKGUGo-Eg&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=10) | [Video - Part #3]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_5.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_5_Notes.pdf")`) |
| [Vergi Örneği](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5_Vergi Ornegi.jpg")`) `r emo::ji(in.progress)` | [Tax Example](`r paste0(economics.path, "Economics_-_Week_5_Tax_Example.jpg")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_5_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_5_Worksheet_Solution.pdf")`) |
| [Çalışma Soruları Cevaplar - Grafiksel](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_5_CS_Cevaplar__Grafiksel.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions - Graphical](`r paste0(economics.path, "Economics_-_Week_5_Worksheet_Solution__Graphical.pdf")`) |

## Week #6
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=QJKhDzAnvRA&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=11) | [Video - Part #1]() `r emo::ji(in.progress)` |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=ebzskGeYMgo&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=12) | [Video - Part #2]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_6.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_6.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_6_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_6_Notes.pdf")`) |
| [Ek Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_6_Ek_Notlar.pdf")`) `r emo::ji(in.progress)` | [Additional Notes](`r paste0(economics.path, "Economics_-_Week_6_Additional_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_6_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_6_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_6_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_6_Worksheet_Solution.pdf")`) |

## Week #7
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=uACsAqu3Z-4&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=13) | [Video - Part #1]() `r emo::ji(in.progress)` |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=Unc85Ih2sIE&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=14) | [Video - Part #2]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_7.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_7.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_7_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_7_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_7_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_7_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_7_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_7_Worksheet_Solution.pdf")`) |

## Week #8
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video](https://www.youtube.com/watch?v=t9v1kjSLpXc&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=15) | [Video]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_8.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_8.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_8_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_8_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_8_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_8_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_8_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_8_Worksheet_Solution.pdf")`) |

## Week #9
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=dfgpxjhMKRo&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=16) | [Video - Part #1]() `r emo::ji(in.progress)` |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=rdzOXmcMAMo&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=17) | [Video - Part #2]() `r emo::ji(in.progress)` |
| [Video - Bölüm #3](https://www.youtube.com/watch?v=xrTe_yBac7E&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=18) | [Video - Part #3]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_9.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_9.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_9_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_9_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_9_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_9_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_9_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_9_Worksheet_Solution.pdf")`) |

## Week #10
| Türkçe `r emo::ji(tr)` | English `r emo::ji(eng)` |
| :--------------------- | :------------------------- |
| [Video - Bölüm #1](https://www.youtube.com/watch?v=yJ7RGbzwUn0&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=19) | [Video - Part #1]() `r emo::ji(in.progress)` |
| [Video - Bölüm #2](https://www.youtube.com/watch?v=P8UYNqkrd8M&list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch&index=20) | [Video - Part #2]() `r emo::ji(in.progress)` |
| [Slaytlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_10.pptx")`) | [Slides](`r paste0(economics.path, "Economics_-_Week_10.pptx")`) |
| [Notlar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_10_Notlar.pdf")`) `r emo::ji(in.progress)` | [Notes](`r paste0(economics.path, "Economics_-_Week_10_Notes.pdf")`) |
| [Çalışma Soruları](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_10_CS.pdf")`) `r emo::ji(in.progress)` | [Worksheet](`r paste0(economics.path, "Economics_-_Week_10_Worksheet.pdf")`) |
| [Çalışma Soruları Cevaplar](`r paste0(ekonomi.path, "Ekonomi_-_Hafta_10_CS_Cevap.pdf")`) `r emo::ji(in.progress)` | [Worksheet Solutions](`r paste0(economics.path, "Economics_-_Week_10_Worksheet_Solution.pdf")`) |
