---
title: Önemli Dokümanlar (İktisat)
linktitle: İktisat
date: "2021-03-04"
lastmod: "2021-03-04"
draft: false
# toc: true
type: docs

menu:
  zaman-serileri-analizi:
    parent: Dokümanlar
    weight: 21

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 21
---

```{r Settings.Emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
İncelediğiniz sayfada `r emo::ji(tr)` <font color="red">**Türkçe**</font>, `r emo::ji(eng)` <font color="red">**İngilizce**</font>, `r emo::ji(to.be.updated)` <font color="red">**Güncellenecek**</font>, `r emo::ji(in.progress)` <font color="red">**Üzerinde Çalışılan**</font> ve `r emo::ji(outdated)` <font color="red">**Artık Geçerli Olmayan**</font> içerikleri ifade eder.
{{% /alert %}}

## Telegram Kanalı
Dersle ilgili önemli duyurulardan zamanında haberdar olabilmeniz için [Telegram](https://telegram.org/) adlı uygulama içinde haberleşme kanalı oluşturulmuştur. Detaylı bilgiye aşağıdaki dokümanlardan ulaşabilirsiniz.  

- [Telegram Kanalı Duyurusu](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_-_Telegram_Kanali_Duyurusu_Bilgilendirme.pdf")`) `r emo::ji(tr)`
- [QR Kod - Telefon İçin](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_-_Telegram_Kanali_Duyurusu_Ilan.pdf")`) `r emo::ji(tr)`

## Ders Planı ve Önemli Günler
| 1. Öğretim | 2. Öğretim | Yaz Okulu |
| :--- | :--- | :--- |
| [Ders Planı](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_1O_-_Ders_Plani.pdf")`) `r emo::ji(tr)` | [Ders Planı](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_2O_-_Ders_Plani.pdf")`) `r emo::ji(tr)` | [Ders Planı](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_-_Ders_Plani.pdf")`) `r emo::ji(tr)` |
| [Önemli Günler](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_1O_-_Onemli_Gunler.pdf")`) `r emo::ji(tr)` | [Önemli Günler](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_2O_-_Onemli_Gunler.pdf")`) `r emo::ji(tr)` | [Önemli Günler](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_-_Onemli_Gunler.pdf")`) `r emo::ji(tr)` |

## Ders Kitabı
- [Kitap Seçimi Açıklaması](`r paste0(zaman.serileri.analizi.path, "Zaman_Serileri_Analizi_-_Kitap_Secimi_Aciklamasi.pdf")`) `r emo::ji(tr)`

## Ders Değerlendirme Anketi
- [Ders Değerlendirme Anketi - Açıklama](`r paste0(zaman.serileri.analizi.path, "EC/Zaman_Serileri_Analizi_-_Ders_Degerlendirme_Anketi.pdf")`) `r emo::ji(tr)`
- [Ders Değerlendirme Anketi - Link](https://forms.gle/9fGgxW3vJkDzjEtWA) `r emo::ji(tr)`
