---
title: Ders Notları
linktitle: Ders Notları
date: "2021-03-04"
lastmod: "2021-03-04"
draft: false
# toc: true
type: docs

menu:
  zaman-serileri-analizi:
    parent: 
    weight: 50

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 50
---

```{r Settings.Emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
İncelediğiniz sayfada `r emo::ji(tr)` <font color="red">**Türkçe**</font>, `r emo::ji(eng)` <font color="red">**İngilizce**</font>, `r emo::ji(to.be.updated)` <font color="red">**Güncellenecek**</font>, `r emo::ji(in.progress)` <font color="red">**Üzerinde Çalışılan**</font> ve `r emo::ji(outdated)` <font color="red">**Artık Geçerli Olmayan**</font> içerikleri ifade eder.
{{% /alert %}}

## Hafta #1
- [Video]() `r emo::ji(tr)``r emo::ji(in.progress)`
- [Slaytlar](`r paste0(zaman.serileri.analizi.path, "Zaman_Serileri_Analizi_-_Hafta_1.pdf")`) `r emo::ji(tr)`
- [Uygulama - HTML](`r paste0(zaman.serileri.analizi.r.link, "Zaman_Serileri_Analizi_-_Hafta_1_Uygulama.html")`) `r emo::ji(tr)`
    + [Uygulama - RMarkdown](`r paste0(zaman.serileri.analizi.r.path, "Hafta_1/", "Zaman_Serileri_Analizi_-_Hafta_1_Uygulama.Rmd")`) `r emo::ji(tr)`
    + [Uygulama - R](`r paste0(zaman.serileri.analizi.r.path, "Hafta_1/", "Zaman_Serileri_Analizi_-_Hafta_1_Uygulama.R")`) `r emo::ji(tr)`
    + [Data - `clean-water.xlsx`](`r paste0(zaman.serileri.analizi.r.path, "Hafta_1/", "clean-water.xlsx")`)
    + [Data - `dam_occupancy.csv`](`r paste0(zaman.serileri.analizi.r.path, "Hafta_1/", "dam_occupancy.csv")`)

## Hafta #2
- [Video]() `r emo::ji(tr)``r emo::ji(in.progress)`
- [Slaytlar](`r paste0(zaman.serileri.analizi.path, "Zaman_Serileri_Analizi_-_Hafta_2.pdf")`) `r emo::ji(tr)`
- [Uygulama - HTML](`r paste0(zaman.serileri.analizi.r.link, "Zaman_Serileri_Analizi_-_Hafta_2_Uygulama.html")`) `r emo::ji(tr)`
    + [Uygulama - RMarkdown](`r paste0(zaman.serileri.analizi.r.path, "Hafta_2/", "Zaman_Serileri_Analizi_-_Hafta_2_Uygulama.Rmd")`) `r emo::ji(tr)`
    + [Uygulama - R](`r paste0(zaman.serileri.analizi.r.path, "Hafta_2/", "Zaman_Serileri_Analizi_-_Hafta_2_Uygulama.R")`) `r emo::ji(tr)`

## Hafta #3
- [Video]() `r emo::ji(tr)``r emo::ji(in.progress)`
- [Slaytlar](`r paste0(zaman.serileri.analizi.path, "Zaman_Serileri_Analizi_-_Hafta_3.pdf")`) `r emo::ji(tr)`
- [Uygulama - HTML](`r paste0(zaman.serileri.analizi.r.link, "Zaman_Serileri_Analizi_-_Hafta_3_Uygulama.html")`) `r emo::ji(tr)`
    + [Uygulama - RMarkdown](`r paste0(zaman.serileri.analizi.r.path, "Hafta_3/", "Zaman_Serileri_Analizi_-_Hafta_3_Uygulama.Rmd")`) `r emo::ji(tr)`
    + [Uygulama - R](`r paste0(zaman.serileri.analizi.r.path, "Hafta_3/", "Zaman_Serileri_Analizi_-_Hafta_3_Uygulama.R")`) `r emo::ji(tr)`
