---
# Course title, summary, and position.
linktitle: "Zaman Serileri Analizi"
summary: "Verildiği son bölüm ve dönem: İktisat - Bahar 2021"
weight: 21
categories: [Ders]
tags: [zaman serileri analizi, türkçe, turkish]

# Page metadata.
title: "Zaman Serileri Analizi"
date: "2021-03-04"
lastmod: "2021-03-04"
draft: false
# toc: true
type: docs  # Do not modify.

# Add menu entry to sidebar.
menu:
  zaman-serileri-analizi:
    name: Zaman Serileri Analizi
    weight: 10
---

<br>

Zaman Serileri Analizi dersine hoş geldiniz!  
Bu dersin amacı zaman serileri analizindeki temel ekonometrik tekniklerin kavramsal ve kısmen uygulamalı olarak incelemek ve tanıtmaktır. Ayrıntılı olarak ele alınacak konu başlıkları arasında zaman serileri ile modelleme ve ilgili varsayımlar bulunmaktadır. Zaman serileri ile alakalı olan trent, mevsimsellik, durağanlık ve birim kök kavramları teorik olarak tanıtıldıktan sonra uygulamalı olarak da incelenecektir. Ekonometri II dersinde tanıtılan otokorelasyon ve değişken varyans kavramlarının zaman serileri modellerinde neden olduğu problemler ve onların çözümleri de hem kavramsal hem de uygulamalı olarak incelenecektir. Ayrıca eşbütünleşme testi ve hata düzeltme modellerinin de üzerinde kısaca durulacaktır.

