---
title: Önemli Dokümanlar (İktisat)
linktitle: İktisat
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  ekonometri-i:
    parent: Dokümanlar
    weight: 21

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 21
---

```{r emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
İncelediğiniz sayfada `r emo::ji(tr)` <font color="red">**Türkçe**</font>, `r emo::ji(eng)` <font color="red">**İngilizce**</font>, `r emo::ji(to.be.updated)` <font color="red">**Güncellenecek**</font>, `r emo::ji(in.progress)` <font color="red">**Üzerinde Çalışılan**</font> ve `r emo::ji(outdated)` <font color="red">**Artık Geçerli Olmayan**</font> içerikleri ifade eder...
{{% /alert %}}

## Telegram Kanalı
Dersle ilgili önemli duyurulardan zamanında haberdar olabilmeniz için [Telegram](https://telegram.org/) adlı uygulama içinde haberleşme kanalı oluşturulmuştur. Detaylı bilgiye aşağıdaki dokümanlardan ulaşabilirsiniz.  

- [Telegram Kanalı Duyurusu](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_Telegram Kanali Duyurusu_Bilgilendirme.pdf")`) `r emo::ji(tr)`
- [QR Kod - Telefon İçin](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_Telegram Kanali Duyurusu_Ilan.pdf")`) `r emo::ji(tr)`

## Ders Planı ve Önemli Günler
| 1. Öğretim | 2. Öğretim | Yaz Okulu |
| :--- | :--- | :--- |
| [Ders Planı](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_1O - Ders Plani (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(to.be.updated)` | [Ders Planı](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_2O - Ders Plani (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(to.be.updated)` | [Ders Planı](`r paste0(ekonometri.i.path, "EC/Ekonometri_I - Ders Plani (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(in.progress)` |
| [Önemli Günler](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_1O - Onemli Gunler (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(in.progress)` | [Önemli Günler](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_2O - Onemli Gunler (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(in.progress)` | [Önemli Günler](`r paste0(ekonometri.i.path, "EC/Ekonometri_I - Onemli Gunler (Kara).pdf")`) `r emo::ji(tr)``r emo::ji(in.progress)` |

## Ders Kitabı
- [Kitap Seçimi Açıklaması](`r paste0(ekonometri.i.path, "Ekonometri_I_Kitap Secimi Aciklamasi (Kara).pdf")`) `r emo::ji(tr)`

## Ders Değerlendirme Anketi
- [Ders Değerlendirme Anketi - Açıklama](`r paste0(ekonometri.i.path, "EC/Ekonometri_I_Ders Degerlendirme Anketi.pdf")`) `r emo::ji(tr)`
- [Ders Değerlendirme Anketi - Link](https://forms.gle/VsT9jjtGospV7DKe8) `r emo::ji(tr)`
