---
title: Önemli Dokümanlar (İktisat)
linktitle: İktisat
date: "2020-10-05"
lastmod: "2020-10-13"
draft: false
# toc: true
type: docs

menu:
  ekonometri-ars-i-ii:
    parent: Dokümanlar
    weight: 21

# Prev/next pager order (if `docs_section_pager` enabled in `params.toml`)
weight: 21
---

```{r Settings.Emoji, include = FALSE}
tr <- "tr"
eng <- "us"
to.be.updated <- "arrows_counterclockwise"
in.progress <- "fire"
outdated <- "no_entry"
```

<br>

{{% alert note %}}
İncelediğiniz sayfada `r emo::ji(tr)` <font color="red">**Türkçe**</font>, `r emo::ji(eng)` <font color="red">**İngilizce**</font>, `r emo::ji(to.be.updated)` <font color="red">**Güncellenecek**</font>, `r emo::ji(in.progress)` <font color="red">**Üzerinde Çalışılan**</font> ve `r emo::ji(outdated)` <font color="red">**Artık Geçerli Olmayan**</font> içerikleri ifade eder.
{{% /alert %}}

## Telegram Kanalı
Dersle ilgili önemli duyurulardan zamanında haberdar olabilmeniz için [Telegram](https://telegram.org/) adlı uygulama içinde haberleşme kanalı oluşturulmuştur. Detaylı bilgiye aşağıdaki dokümanlardan ulaşabilirsiniz.  

- [Telegram Kanalı Duyurusu](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_I-II_-_Telegram_Kanali_Duyurusu_Bilgilendirme.pdf")`) `r emo::ji(tr)`
- [QR Kod - Telefon İçin](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_I-II_-_Telegram_Kanali_Duyurusu_Ilan.pdf")`) `r emo::ji(tr)`

## Ders Planı ve Önemli Günler
#### Ekonometri Araştırmaları I
- [Ders Planı](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_I_-_Ders_Plani.pdf")`) `r emo::ji(tr)`
- [Önemli Günler](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_I_-_Onemli_Gunler.pdf")`) `r emo::ji(tr)`

#### Ekonometri Araştırmaları II
- [Ders Planı](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_II_-_Ders_Plani.pdf")`) `r emo::ji(tr)`
- [Önemli Günler](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_II_-_Onemli_Gunler.pdf")`) `r emo::ji(tr)`

## Doldurulması Gereken Formlar
- [Danışman Öğrenci Sözleşmesi Formu - Güz](`r paste0(ekonometri.ars.path, "EC/1_-_Danisman-Ogrenci-Sozlesmesi-Formu_-_Guz.docx")`) `r emo::ji(tr)`
- [Danışman Öğrenci Sözleşmesi Formu - Bahar](`r paste0(ekonometri.ars.path, "EC/1_-_Danisman-Ogrenci-Sozlesmesi-Formu_-_Bahar.docx")`) `r emo::ji(tr)`
- [Yapay Zeka Kullanım Beyanı - Güz ve Bahar](`r paste0(ekonometri.ars.path, "EC/3_-_Yapay-Zeka-Kullanim-Beyani.docx")`) `r emo::ji(tr)`
- [Yazım Şablonu Kontrol Listesi - Güz ve Bahar](`r paste0(ekonometri.ars.path, "EC/4_-_Yazim-Sablonu-Kontrol-Listesi.docx")`) `r emo::ji(tr)`
- [Haftalık İlerleme Raporu - Güz ve Bahar](`r paste0(ekonometri.ars.path, "EC/5_-_Haftalik-Ilerleme-Raporu.docx")`) `r emo::ji(tr)`

## Ders Kaynakları
- [Kaynakların Açıklaması](`r paste0(ekonometri.ars.path, "Ekonometri_Ars_I-II_-_Kaynaklarin_Aciklamasi.pdf")`) `r emo::ji(tr)`

## Ders Değerlendirme Anketi
- [Ders Değerlendirme Anketi - Açıklama](`r paste0(ekonometri.ars.path, "EC/Ekonometri_Ars_I-II_-_Ders_Degerlendirme_Anketi.pdf")`) `r emo::ji(tr)`
- [Ders Değerlendirme Anketi - Link](https://forms.gle/Xd6Le8FnZ7sitfzN6) `r emo::ji(tr)`
