---
# Course title, summary, and position.
linktitle: "Dönem Projesi"
summary: "Verildiği son bölüm ve dönem: İktisat (YL) - Güz 2024"
weight: 32
categories: [Ders]
tags: [dönem projesi, türkçe, turkish]

# Page metadata.
title: "Dönem Projesi"
date: "2023-09-23"
lastmod: "2023-09-23"
draft: false
# toc: true
type: docs  # Do not modify.

# Add menu entry to sidebar.
menu:
  donem-projesi:
    name: Dönem Projesi
    weight: 10
---

<br>

Dönem Projesi dersine hoş geldiniz!  
Bu dersin ilk amacı ekonomi ile alakalı olan bir problemi/soruyu ortaya koyup daha sonra bu problemle/soruyla alakalı test etmek istediğiniz hipotezi oluşturmaktır. Dersin nihai amacı ise daha önceki derslerde öğrendiğiniz ekonometri biliminin temel ilkelerini kullanarak bu hipotezi test etmektir. Dönem Projesi dersi boyunca öğrenciler ortaya koydukları bu problemi/soruyu araştırarak ve uygulayarak adım adım akademik bir makaleye dönüştüreceklerdir. Daha sonra, Sosyal Bilimler Enstitüsü’ne ait “[Tezsiz Yüksek Lisans Programı Süreçleri](https://sosbilen.ogu.edu.tr/Sayfa/Index/637/tezsiz-yuksek-lisans-programi-surecleri)” sayfasındaki “[Tez ve Dönem Projesi Yazım ve Basım Yönergesi](https://sosbilen.ogu.edu.tr/Storage/SosBilEn/Uploads/tez_donem_projesi_yazim_yonergesi.pdf)” ve “[Dönem Projesi Yazım Kılavuzu](https://sosbilen.ogu.edu.tr/Storage/SosBilEn/Uploads/donem_projesi_yazim_kilavuzu.docx)” linklerindeki belgeleri kullanarak yazdıkları akademik makaleyi dönem projesi olarak Sosyal Bilimler Enstitüsü’ne teslim edeceklerdir.
