---
slug: ders-anlatimi-ornek
title: Ders Anlatımı (Örnek)
subtitle: ""
summary: "Akademi Ekonometri olarak video va not paylaşımında bulunacağımız derslerle ilgili kısa bir ön gösterim yapalım dedik."
categories: [ders]
tags: [örnek gönderi, pdf, slayt, video]
author: Akademi Ekonometri
authors: [Akademi Ekonometri]
date: "2020-10-05"
lastmod: "2020-10-06T09:54:28+03:00"
publishDate: ""
featured: false
disable_jquery: false
image:
  caption: "[Photo from Unsplash](https://unsplash.com/)"
  focal_point: ""
  preview_only: false
projects: []
# output:
#   blogdown::html_page:
#     number_sections: true
#     toc: true
#     toc_depth: 2
#     mathjax: local
#     self_contained: false
disable_codefolding: false ## Set to true to disable code folding.
codefolding_show: "show" ## Set to "hide" or "show" all codes by default.
codefolding_nobutton: false ## Set to true to exclude the "Show/hide all" button.
---

Daha [önceki blog yazımızda](/post/yakinda-yayindayiz/) [YouTube kanalımızdaki](https://www.youtube.com/c/AkademiEkonometri) ders (ekonometri ve ekonomi) videolarını ve kulladığımız ders notlarını paylaşacağımızdan bahsetmiştik. Aşağıdaki bölümlerde [Ekonometri II](/courses/ekonometri-ii/), [Ekonomi](/courses/ekonomi/) ve [Economics](/courses/economics/) derslerine ait örnek ders notlarına ve videolarına erişebilrisiniz.

## Ekonometri II Dersi
Örnek Ekonometri II ders videosunu ve notunu aşağıda bulabilirsiniz.  
- [Ders Notu](Ekonometri_II - Hafta 1 (Kara).pdf)  
- [Video](https://youtu.be/cGjkSr9Woe0?list=PLGdlUqXbpitlL_CbPiev5Lu0j3dKvQq7x)  
<iframe width="720" height="405" src="https://www.youtube.com/embed/cGjkSr9Woe0?list=PLGdlUqXbpitlL_CbPiev5Lu0j3dKvQq7x" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  

## Ekonomi Dersi
Örnek Ekonomi ders videosunu ve slaytlarını aşağıda bulabilirsiniz.  
- [Ders Slaytları (Türkçe)](Ekonomi - Hafta 1 (Kara).pptx)  
- [Video (Türkçe)](https://youtu.be/2X_-CiNAr6w?list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch)  
<iframe width="720" height="405" src="https://www.youtube.com/embed/2X_-CiNAr6w?list=PLGdlUqXbpitn_vnaxzj2qx18n5f4P7qch" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  

## Economics Dersi
Örnek Economics ders videosunu ve slaytlarını aşağıda bulabilirsiniz.  
- [Ders Slaytları (İngilizce)](Economics - Week 1 (Kara).pptx)  
- [Video (İngilizce)](https://youtu.be/rEZfMve6Vm0?list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg)  
<iframe width="720" height="405" src="https://www.youtube.com/embed/rEZfMve6Vm0?list=PLGdlUqXbpitlXmYoB4LUc2dnnI1OPAhHg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  

